name: TanoRPG
version: ${project.version}
main: com.github.tanokun.tanorpg.TanoRPG
api-version: 1.15
depend: [ Vault, Citizens, ProtocolLib, MythicMobs, WorldGuard, LuckPerms, HolographicDisplays, CommandAPI]
softdepend:
  - ThirdParty